name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  binaries:
    name: Goreleaser release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parca-debuginfo-dist-release
          if-no-files-found: error
          path: |
            dist/

  docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    needs: binaries
    steps:
      - uses: actions/checkout@v4

      - name: Publish Vercel
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_WEBHOOK }}"
